# Next steps

```{r, include = FALSE}
knitr::opts_chunk$set(fig.width=6, fig.height=3.5, fig.align="center", comment="    ")
```

## Deepen your understanding

**Our number one recommendation is to read the book ["R for Data Science"](http://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham.**

Also, statistical tasks such as model fitting, hypothesis testing, confidence interval calculation, and prediction are a large part of R, and one we haven't demonstrated fully today. "Modern Applied Statistics with S" by W.N. Venable and B.D. Ripley is a well respected reference covering R and its predecessor S. "Linear Models with R" and "Extending the Linear Model with R" by Julian J. Faraway cover linear models, with many practical examples. Linear models, and the linear model formula syntax `~`, are core to much of what R has to offer statistically. Many statistical techniques take linear models as their starting point, including `limma` for differential gene expression, `glm` for logistic regression (etc), survival analysis with `coxph`, and mixed models to characterize variation within populations.


## Expand your vocabulary

Have a look at these cheat sheets to see what is possible with R.

* [RStudio's collection of cheat sheets](https://www.rstudio.com/resources/cheatsheets/) cover newer packages in R.
* [An old-school cheat sheet](https://cran.r-project.org/doc/contrib/Short-refcard.pdf) for dinosaurs and people wishing to go deeper.
* [Bioconductor cheat sheet](https://github.com/mikelove/bioc-refcard/blob/master/README.Rmd) for biological data.


## Join the community

Join the [Data Fluency community at Monash](https://monashdatafluency.github.io/).

 * Mailing list for workshop and event announcements.
 * Slack for discussion.
 * Drop-in sessions on Friday afternoon.

Meetups in Melbourne:

* [MelbURN](https://www.meetup.com/en-AU/MelbURN-Melbourne-Users-of-R-Network/)
* [R-Ladies](https://www.meetup.com/en-AU/R-Ladies-Melbourne/)

For bioinformatics, [COMBINE](https://combine.org.au/) is a student and early career researcher organization, and runs Software Carpentry workshops.

